//Generated by Prefab3D 2.143, Tue Jun 4 04:13:04 GMT+0300 2013. www.closier.nl/prefab

//For educational purpose, this class demonstrates how to use Prefab3D's exports, (AS3, guys API, lights etc...)
//and the way they could be implemented into your project.

package 
{
	//[SWF(width="800", height="600", frameRate="60")]

	import Cup;

	import away3d.containers.View3D;
	import away3d.cameras.Camera3D;
	import away3d.cameras.lenses.PerspectiveLens;

	import flash.display.Sprite;
	import flash.events.Event;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;

	public class PrefabProject extends Sprite
	{
		private var _view : View3D;
		private var _prefabOutput:Cup;
		private var _camera:Camera3D;

		public function PrefabProject() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}

		private function init(e:Event):void
		{
			removeEventListener(Event.ADDED_TO_STAGE, init);
			stage.align = StageAlign.TOP_LEFT;
			stage.scaleMode = StageScaleMode.NO_SCALE;
			stage.showDefaultContextMenu = true;
			stage.stageFocusRect = false;

			initView();
            initCamera();

			stage.addEventListener(Event.RESIZE, onResize);

			var skyBoxData:SkyBoxData = new SkyBoxData();
			skyBoxData.build(_view.scene);
			initContent();
			addEventListener(Event.ENTER_FRAME, renderFrame);
		}

		private function initView():void
		{
			_view = new View3D();
			_view.antiAlias = 2;
			_view.backgroundColor = 0x222222;
            addChild(_view);
		}

        private function initCamera():void {
            _camera = _view.camera;
            _camera.lens = new PerspectiveLens();
            _camera.lens.near = 10;
            _camera.lens.far = 50000;

            _camera.x = 138.86524963378906;
            _camera.y = 344.0169677734375;
            _camera.z = -626.3806762695313;
        }

		private function initContent():void
		{
			_prefabOutput = new Cup();
			_view.scene.addChild(_prefabOutput);
			_camera.lookAt(_prefabOutput.position);

		}

		public function renderFrame(e:Event):void
		{
			 _view.render();
		}

		private function onResize(event:Event):void
		{
			_view.width = stage.stageWidth;
			_view.height = stage.stageHeight;
		}

	}
}