//Generated by Prefab3D 2.143, Tue Jun 4 04:13:04 GMT+0300 2013. www.closier.nl/prefab
package 
{
	import away3d.primitives.SkyBox;
	import away3d.materials.SkyBoxMaterial;
	import away3d.textures.BitmapCubeTexture;
	import away3d.containers.Scene3D;

	import flash.display.BitmapData;
	import flash.display.Bitmap;

	public class SkyBoxData
	{
		[Embed(source= "images/sbpositiveX.jpg")]
		private var _positiveX:Class;
		[Embed(source= "images/sbnegativeX.jpg")]
		private var _negativeX:Class;
		[Embed(source= "images/sbpositiveY.jpg")]
		private var _positiveY:Class;
		[Embed(source= "images/sbnegativeY.jpg")]
		private var _negativeY:Class;
		[Embed(source= "images/sbpositiveZ.jpg")]
		private var _positiveZ:Class;
		[Embed(source= "images/sbnegativeZ.jpg")]
		private var _negativeZ:Class;

		public function SkyBoxData(){}

		public function build(scene:Scene3D):void
		{
			var embeds:Array = [_positiveX, _negativeX, _positiveY, _negativeY, _positiveZ, _negativeZ];
			var mapsIDs:Array = ["positiveX", "negativeX", "positiveY", "negativeY", "positiveZ", "negativeZ"];

			var bmd:BitmapData = Bitmap(new embeds[0]()).bitmapData;
			var bct:BitmapCubeTexture = new BitmapCubeTexture(bmd, bmd, bmd, bmd, bmd, bmd);
			for(var i:uint = 1;i<6;++i){
				bmd = Bitmap(new embeds[i]()).bitmapData;
				bct[mapsIDs[i]] = bmd;
			}

			var skyBox:SkyBox = new SkyBox(bct);
			scene.addChild(skyBox);
		}
	}
}
