////Generated by Prefab3D 2.143, Tue Jun 4 05:00:10 GMT+0300 2013. www.closier.nl/prefab
package data {

	import away3d.core.base.Geometry;
	import data.ASDReader;

	public class Obj_000001Data {

		[Embed(source="asd/Obj_000001Data.asd", mimeType="application/octet-stream")]
		private var Obj_000001DataASD:Class;

		public function get geometryData():Geometry
		{
			return ASDReader.decodeGeometry(new Obj_000001DataASD());
		}

	}
}